### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jpincas** [bradleypeabody/gouuidv6#1]
Couldn't find a contact email for you.

Just wanted to say thanks for this package.  I was looking for timestamp-ordered UUIDs for use in https://github.com/jpincas/tormenta and this fit the bill perfectly.

Feel free to delete this issue once you've given yourself a pat on the back!!

Jon

**Comment by bradleypeabody** [comment]
Haha, thanks Jon.  Glad you found it useful.
